import {
  Utensils,
  Car,
  Zap,
  ShoppingBag,
  Plus,
  Gamepad2,
  Book,
  User,
  MoreHorizontal,
  Briefcase,
  Laptop,
  TrendingUp,
  ArrowUpRight,
  PlusCircle,
  ArrowUpDown,
  ArrowDownCircle,
  Banknote,
  Building2,
  Smartphone,
  CreditCard,
  Lock,
  Trash2,
  Pencil,
  Eye,
  EyeOff,
  ChevronRight,
  Check,
  X,
  Target,
  Archive,
  Calendar,
  Upload,
  Table2,
  Download,
  CircleDollarSign,
  BarChart2,
  HelpCircle,
  Wallet,
  LucideProps,
} from 'lucide-react';
import React from 'react';

export const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  utensils: Utensils,
  car: Car,
  zap: Zap,
  'shopping-bag': ShoppingBag,
  plus: Plus,
  'gamepad-2': Gamepad2,
  book: Book,
  user: User,
  'more-horizontal': MoreHorizontal,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  'arrow-up-right': ArrowUpRight,
  'plus-circle': PlusCircle,
  'arrow-up-down': ArrowUpDown,
  'arrow-down-circle': ArrowDownCircle,
  banknote: Banknote,
  'building-2': Building2,
  smartphone: Smartphone,
  'credit-card': CreditCard,
  lock: Lock,
  trash2: Trash2,
  pencil: Pencil,
  eye: Eye,
  eyeoff: EyeOff,
  chevronright: ChevronRight,
  check: Check,
  x: X,
  target: Target,
  archive: Archive,
  calendar: Calendar,
  upload: Upload,
  table2: Table2,
  download: Download,
  circledollarsign: CircleDollarSign,
  barchart2: BarChart2,
  wallet: Wallet,
};

export function getCategoryIcon(name: string): React.ComponentType<LucideProps> {
  const icon = iconMap[name.toLowerCase()];
  return icon || HelpCircle;
}
